#-------------------------------
# Site Settings
title: "Jishnu's Systems Immunology Lab"
description: The lab
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "News"
      url: "/news/"
    - title: "Publications"
      url: "/posts/"
    - title: "Team"
      url: "/team/"
    - title: "Contact us"
      url: "/Contact-us/"


# Call to action button
cta_button:
  enable: False
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Author Settings
author:
  author_name: "Jishnu Das"
  author_avatar: "/images/das_head.webp"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Machine Learning, Networks, Immunology, Coffee and Music
  hero_description: Leveraging diverse expertise to pioneer method development and apply practical solutions to diverse biological challenges!

# Hero Logos
hero_logos:
  enable: true

hero_logo_image:
  - alt: "AI Logo"
    image: "/images/ai-svgrepo-com.svg"

  - alt: "immune Logo"
    image: "/images/imm-svgrepo-com.svg"

  - alt: "DL Logo"
    image: "/images/deep-learning-svgrepo-com.svg"

  - alt: "coffee Logo"
    image: "/images/coffee-cup-tea-svgrepo-com.svg"

  - alt: "robot Logo"
    image: "/images/robot-ai-svgrepo-com.svg"

  - alt: "DNA Logo"
    image: "/images/dna-svgrepo-com.svg"

  - alt: "immune defense Logo"
    image: "/images/immune-system-immunity-defense-svgrepo-com.svg"


#-------------------------------
# Slider Featured Settings
featured:
  enable: true
  featured_intro: Top Pick's
  featured_title: Selected Work


#-------------------------------
# Blog Section Settings
blog:
  enable: false
  blog_intro: What‚Äôs new?
  blog_title: Latest publications


#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: False
  testimonials_intro: Some famous quotes of our lab
  testimonials_title: See what our lab members say...
  testimonials_info: Join us for <b>more</b> famous lab quotes and stories

testimonial_items:
  - name: "Swapnil Keshri"
    image: "/images/swapnil.webp"
    designation: "CPCB Phd Student"
    title: "Major update coming soon"
    content : "As a dynamic and ever-growing laboratory, we actively engage with a diverse array of research challenges presented to us. We are committed to maximizing our efforts to derive optimal outcomes from each endeavor and provide major updates on the projects we are working on."

  - name: "Javad Rahimikollu"
    image: "/images/javad.webp"
    designation: "CPCB Phd Student"
    title: "Try running SLIDE on your data...."
    content : "The members of our lab developed a first-in-class interpretable machine learning technique for identifying significant interacting latent factors underlying outcomes of interest from high-dimensional omic datasets which we apply on most of our datasets."

  - name: "Simar Yadav"
    image: "/images/simar.webp"
    designation: "Research Scholar"
    title: "Manchester United is the best premier league Team!!"
    content : "Manchester United has a rich history and a strong tradition in English football. The club has a storied past, filled with numerous titles, legendary players, and iconic moments.All of us consider this a fact(also young Cristiano Ronaldo was the best footballer)"

  - name: "Jishnu Das"
    image: "/images/Jishnu-Das-2.jpg"
    designation: "Principal Investigator, Assistant Professor"
    title: "Do you want an espresso??"
    content : "Before delving into a substantial discussion with Jishnu, it has become a customary ritual for us to graciously accept the coffee he generously offers, setting the tone for our exchange and fostering an environment of conviviality and collaboration."

#-------------------------------
# Author Section Settings
author_section:
  enable: true
  author_section_title: "Hi there ! üëã Welcome to Jishnu's Systems Immunology Lab."
  author_section_description: "As a computational systems immunology lab, our research focuses on the development and use of novel systems approaches to analyze high-dimensional immunological datasets, and elucidate molecular mechanisms of immunological disorders. We are currently working on using network systems and functional genomic approaches to perform multi-scale integration of genomic and epigenomic datasets with biological networks to identify molecular phenotypes underlying these immunological disorders. We also use statistical and machine-learning techniques to integrate multi-omic datasets (genomic, transcriptomic, proteomic, metabolomic and antibody-omic) and elucidate molecular mechanisms of immune regulation and dysregulation."
  author_section_image: "/images/lab_photo.JPG"
  author_section_image_alt: Daryl Mercer
  author_section_button_text: Let's —Åonnect!
  author_section_button_link: "/contact/"


#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    - title: "News"
      url: "/news/"
    - title: "Publications"
      url: "/posts/"
    - title: "Team"
      url: "/team/"
    - title: "Contact us"
      url: "/Contact-us/"

# Social Links
social:
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-tiktok", name: "Tiktok", link: "https://www.tiktok.com"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay inspired weekly üì¨ Your friendly dose of tips & insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address


#-------------------------------
# Contact Settings
contact:
  email: simar8yadav@gmail.com # Add your form_id
  description: "Get in touch with us to inquire about our services or to connect with our team. Whether you have questions, feedback, or simply want to learn more about what we do, we're here to help. Reach out to us today!" # Add a description of your form

# NOTE
# Gerous theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id